[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "abacusai>=1.4.44",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
