[project]
name = "AbacusAI_Deployment"
version = "0.1.0"
description = ""
authors = ["Pakorngrid>"]
requires-python = ">=3.11"
dependencies = [
    "abacusai>=1.4.44",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
